### ISSUE TITLE
Move website design away from "one big page" with tab-based navigation to multiple separate pages with the same style/theme

### ISSUE THREAD

**Issue by andy11** [andy11/ScriptObservatory#1]
Pages:
- Home
- How does it work?
- Explore the data
- Suggest webpages to observe
- Get involved
- Blog

**Comment by mekhami** [comment]
Why do you want different pages?

**Comment by andy11** [comment]
The main reason I was wanting to move to separate pages was to make it possible to directly link to a given page (or tab).

For example, if I wanted to send someone a URL that linked directly to the "Explore the Data" tab, currently there's not a good way to do that. 

I did a bit of hacky JavaScript to make query URLs work (https://scriptobservatory.org/?query=testwebsite.com, for example), but that doesn't seem like a good long-term design.

If you can think of a way to keep the current design as-is, but have make each tab/page directly linkable, that would be great! :)

Let me know if you had any other thoughts, too

**Comment by mekhami** [comment]
Sure, I'm also not familiar with Angular but I'm thinking it should be relatively easy to break this out into new pages... I'll probably have a PR in sometime next week.

**Comment by andy11** [comment]
Awesome, thanks! 

I'll assign this to you so others don't work on it in the meantime. Shoot me an email if you have any thoughts / questions while working.

**Comment by andy11** [comment]
Hey just checking in. Any updates / issues?

**Comment by mekhami** [comment]
Hey, had a memorial day holiday but will try to get something done on this
this weekend.

**Comment by andy11** [comment]
Oh ok, great. Thanks!

**Comment by andy11** [comment]
Hey, I'm gonna close this (want to stick with the current design a little longer), but let me know if you're still interested in getting involved. There's lots of other areas that could use work.
