### ISSUE TITLE
Blog posts! (want to reverse-engineer some bad JavaScript?)

### ISSUE THREAD

**Issue by andy11** [andy11/ScriptObservatory#3]
If you're interested in analyzing some of the JavaScript samples that have been captured on ScriptObservatory, please get in touch. 

If you do a write-up that explains how the JS works, I'll put it on the ScriptObservatory website as a blog post. You can give a shout-out your own website or project and cross-post it there, too.

**YOU DON'T NEED TO BE A PROFESSIONAL REVERSE-ENGINEER TO DO ONE OF THESE!** 

If this sounds interesting but you aren't sure where to start, just send me an email (andy@andymartin.cc).

The way I'd like this to work is:
- You look through samples of interesting JavaScript (I'll post ones I think make good candidates as comments on this issue)
- You post a comment saying you're going to work on Sample X. (you can also send me an email)
- You have 7 days to send me a write-up for it. If a week goes by and you lose interest / don't finish, the piece of JS gets opened back up for anyone to work on. 
- If you send me a draft and we decide there's more to do, the 7 days can be extended. 

Feel free to reach out as you work on it and get early feedback from me / everyone else.

Thanks!

**Comment by andy11** [comment]
SAMPLE #1:

https://scriptobservatory.org/script-content/6c83bafb233d9e05b7b7a945b4b4f9355bbc4a39b0982c8e250723f6b8c2f4d3

**Comment by ThreatActor** [comment]
https://corered.com/blog/2015/05/24/scriptobservatory-org-check-for-javascript-malware/

**Comment by andy11** [comment]
Thanks! Will follow up with you on a few things via email.

I'm hoping to have a "blog" section up on the site in the next week.

**Comment by andy11** [comment]
I'll open a new issue for each piece of bad javascript going forward.

**Comment by ThreatActor** [comment]
I pull requested to I can add to the codes as well,
and I found out away to bypass spam filter for live + yahoo+ AOL + too many
but google still keep my email in the inbox but with note


On Sat, May 30, 2015 at 8:48 AM, andy11 <notifications@github.com> wrote:

> I'll open a new issue for each piece of bad javascript going forward.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andy11/ScriptObservatory/issues/3#issuecomment-107056153>
> .
>



-- 
ThreatActor
Zed H
CoreRED.com
